import type { Metadata } from "next";
import { Inter, Roboto_Mono,Geist,Poppins  } from "next/font/google";
import "./globals.css";
import 'leaflet/dist/leaflet.css';

const poppins = Poppins({
  weight: '700',
  subsets: ['latin'],

});
 

export const metadata: Metadata = {
  title: "MH Boutique",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={`${poppins.className}`}>

<head>
        {/* Add the Devicon CSS link */}
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/devicons/devicon@master/devicon.min.css"
        />
      </head>
      <body>{children}</body>
    </html>
  );
}
